name = "ReactiveObjects"
uuid = "47fa113f-da65-44bb-8fb0-07b53f5ab554"
authors = ["Nikolas Siccha <nikolassiccha@gmail.com>"]
version = "0.1.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
